# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/uis/list_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_list_selector(object):
    def setupUi(self, list_selector):
        list_selector.setObjectName("list_selector")
        list_selector.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(list_selector)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_instruction = QtWidgets.QLabel(list_selector)
        self.label_instruction.setObjectName("label_instruction")
        self.horizontalLayout_2.addWidget(self.label_instruction)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.list = QtWidgets.QListView(list_selector)
        self.list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list.setObjectName("list")
        self.horizontalLayout.addWidget(self.list)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbutton_create = QtWidgets.QPushButton(list_selector)
        self.pbutton_create.setObjectName("pbutton_create")
        self.verticalLayout.addWidget(self.pbutton_create)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pbutton_accept = QtWidgets.QPushButton(list_selector)
        self.pbutton_accept.setObjectName("pbutton_accept")
        self.verticalLayout.addWidget(self.pbutton_accept)
        self.pbutton_cancel = QtWidgets.QPushButton(list_selector)
        self.pbutton_cancel.setObjectName("pbutton_cancel")
        self.verticalLayout.addWidget(self.pbutton_cancel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(list_selector)
        QtCore.QMetaObject.connectSlotsByName(list_selector)

    def retranslateUi(self, list_selector):
        _translate = QtCore.QCoreApplication.translate
        list_selector.setWindowTitle(_translate("list_selector", "Selection"))
        self.label_instruction.setText(_translate("list_selector", "Select an item:"))
        self.pbutton_create.setText(_translate("list_selector", "Create"))
        self.pbutton_accept.setText(_translate("list_selector", "Accept"))
        self.pbutton_cancel.setText(_translate("list_selector", "Cancel"))
