
# this did not work. It builds the docker, but the applications cannot find the PyQt5 modules
# separate installation of PyQt5 did not help

#FROM ubuntu:latest
ARG PYTHON_BASE=3.12-slim
# build stage
FROM python:$PYTHON_BASE AS builder

LABEL authors="Heinz Preisig"
WORKDIR /project/tasks
COPY . /project



RUN #apt-get update && apt-get install -y python3-pip
RUN pip install pdm
RUN pdm install


# disable update check
ENV PDM_CHECK_UPDATE=true


# copy files
COPY pyproject.toml pdm.lock README.md /project/
FROM python:$PYTHON_BASE
# retrieve packages from build stage
COPY --from=builder /project/.venv /project/.venv
ENV PATH="/project/.venv/bin:$PATH"

ENV PYTHONPATH="/project/.venv/lib/python3.12/site-packages:$PYTHONPATH"

# set command/entrypoint, adapt to fit your needs

WORKDIR /ProMo
COPY ./tasks/ tasks/
COPY ./packages/ packages/
COPY ./src/ src/


VOLUME /tmp/.X11-unix

# Set the DISPLAY environment variable
ENV DISPLAY=:0

# Allow the container to connect to the host machine's display
#CMD ["your_qt_application"]

ENV QT_QPA_PLATFORM=xcb

RUN chmod +x tasks/task.sh


#EXPOSE 8000

WORKDIR /ProMo/tasks
CMD ["bash", "task.sh"]



#ENTRYPOINT ["top", "-b"]