"""Contains functions to perform Input/Output"""
# TODO Move this file to correct location.

import json
from typing import List, Dict, Optional

from packages.Common.classes import equation
from packages.Common.classes import entity
from packages.Common.classes import variable
from packages.Common import resource_initialisation


def fix_entities_in_file(ontology_name: str) -> None:
  """Converts all integers to strings in the entity file.

  Used to convert old files generated by the entity_behaviour module.

  Args:
      ontology_name (str): Name of the ontology.
  """
  path = resource_initialisation.FILES[
    "variable_assignment_to_entity_object"
  ] % ontology_name

  with open(path, "r", encoding="utf-8",) as file:
    main_data = json.load(file)

  data = main_data["behaviours"]

  for variant in main_data["behaviours"]:
    data = main_data["behaviours"][variant]

    for element in data["IDs"]:
      data["IDs"][element] = str(data["IDs"][element])

    new_blocked = []
    for element in data["blocked"]:
      new_blocked.append(str(element))
    data["blocked"] = new_blocked

    new_init = []
    for element in data["to_be_initialised"]:
      new_init.append(str(element))
    data["to_be_initialised"] = new_init

    data["root_variable"] = str(data["root_variable"])
    data["root_equation"] = str(data["root_equation"])

    tree = data["tree"]
    for node_id in tree:
      new_ancestors = []
      for element in tree[node_id]["ancestors"]:
        new_ancestors.append(str(element))
      tree[node_id]["ancestors"] = new_ancestors

      new_children = []
      for element in tree[node_id]["children"]:
        new_children.append(str(element))
      tree[node_id]["children"] = new_children

  with open(path, "w", encoding="utf-8") as outfile:
    json.dump(main_data, outfile, indent=4)

def load_equations_from_file(
  ontology_name: str,
  eq_ids: Optional[List[str]] = None
) -> Dict[str, equation.Equation]:
  """Loads data from file to create Equation objects.

  Args:
      ontology_name (str): Name of the ontology.
      eq_ids (Optional[List[str]], optional): Ids of the equations that
        will be loaded. If **None** all equations will be loaded.
        Defaults to **None**.

  Returns:
      Dict[str, equation.Equation]: Data of the equations. The keys are
        the  equation ids and the corresponding values are Equation
        objects.
  """
  path = resource_initialisation.FILES[
    "global_equation_id"
  ] % ontology_name
  with open(path, "r", encoding="utf-8",) as file:
    data = json.load(file)

  if eq_ids is None:
    eq_ids = data.keys()

  # TODO Remove when compatibility is not an issue anymore.
  temp = []
  for eq_id in eq_ids:
    if "E_" in eq_id:
      temp.append(eq_id)
    else:
      temp.append("E_" + eq_id)
  eq_ids = temp

  equations = {}
  for eq_id in eq_ids:
    # TODO Change from eq_id.replace("E_", "") to eq_id when is no
    # longer necessary.
    if eq_id.replace("E_", "") not in data:
      print(eq_id + " not found.")
      continue

    # TODO Change from eq_id.replace("E_", "") to eq_id when is no
    # longer necessary.
    equations[eq_id] = equation.Equation.from_dict(
      eq_id,
      data[eq_id.replace("E_", "")]
    )

  return equations

def load_entities_from_old_file(
  ontology_name: str,
  all_equations: Dict[str, equation.Equation],
  entity_names: Optional[List[str]] = None
) -> Dict[str, entity.Entity]:
  """Loads data from file to create Entity objects.

  Args:
      path (str): Path to the entity file.
      all_equations (Dict[str, equation.Equation]): All the equations
          in the Ontology. The keys are equation ids and the values are
          Equation objects.
      entity_names (list[str]): Names of the entities that will be
      loaded. If **None** all entities are loaded. Defaults to **None**.

  Returns:
      list[Entity]: Contains instances of Entity with data loaded from
        the specified file.

  Args:
      ontology_name (str): Name of the ontology.
      all_equations (Dict[str, equation.Equation]): Data of all
        equations. The keys are the equation ids and the corresponding
        values are Equation objects.
      entity_names (Optional[List[str]], optional): Names of the
        entities that will be loaded. If **None** all entities are
        loaded. Defaults to **None**.

  Returns:
      Dict[str, entity.Entity]: Data of the entities. The keys are
        the names of the entities and the corresponding values are
        Entity objects.
  """
  path = resource_initialisation.FILES[
    "variable_assignment_to_entity_object"
  ] % ontology_name
  with open(path, "r", encoding="utf-8",) as file:
    data = json.load(file)

  # TODO Change behaviour in case of no data.
  if not data:
    return {}

  # TODO Remove this when is not loger needed for compatibility
  data = data["behaviours"]

  if entity_names is None:
    entity_names = data.keys()

  entities = {}
  for ent_name in entity_names:
    if ent_name not in data:
      print(ent_name + " not found.")
      continue

    new_entity = entity.Entity.from_old_dict(
      ent_name,
      data[ent_name],
      all_equations,
    )
    # TODO Check why it cant be stored as base#
    if "base_" in ent_name:
      ent_name = ent_name.replace("base_", "base#")

    entities[ent_name] = new_entity

  return entities

def load_variables_from_old_file(
  ontology_name: str,
  variable_ids: Optional[List[str]] = None
) -> Dict[str, entity.Entity]:
  """Loads data from file to create Variable objects.

  Args:
      ontology_name (str): _description_
      variable_names (Optional[List[str]]): Ids of the variables that
      will be loaded. If **None** all variables are loaded. Defaults to
      **None**.

  Returns:
      Dict[str, entity.Entity]: Data of the variables. The keys are
        the ids of the variables and the corresponding values are
        Variable objects.
  """

  path = resource_initialisation.FILES["variables_file"] % ontology_name
  with open(path, "r", encoding="utf-8",) as file:
    data = json.load(file)

  # TODO Change behaviour in case of no data.
  if not data:
    return {}

  # TODO Remove this when is not loger needed for compatibility
  data = data["variables"]

  if variable_ids is None:
    variable_ids = data.keys()

  variables = {}
  for variable_id in variable_ids:
    var_id = variable_id
    if "V_" not in var_id:
      var_id = "V_" + var_id

    old_id = var_id.replace("V_", "")
    if old_id not in data:
      print(old_id + " not found.")
      continue

    new_var = variable.Variable.from_old_dict(
      var_id,
      data[old_id],
    )

    variables[var_id] = new_var

  return variables

def save_entities_to_old_file(
    ontology_name: str,
    entities: Dict[str, entity.Entity],
  ) -> None:

  path = resource_initialisation.FILES[
    "variable_assignment_to_entity_object"
  ] % ontology_name
  data = {"behaviours": entities}

  with open(path, "w", encoding="utf-8",) as file:
    json.dump(data, file, cls=EntityJSONEncoderOld, indent=2)

class EquationJSONEncoder(json.JSONEncoder):
  """Custom encoder for Equation objects."""
  def default(self, o):
    """Represents data from Equation objects as a dictionary.

    Args:
        obj (Equation): Equation object that will be encoded.

    Returns:
        dict: The dictionary representation of the Equation object. If
          the object is not an Equation instance then the default
          representation is returned.
    """
    if isinstance(o, equation.Equation):
      return o.convert_to_dict()
    return super().default(o)

class EntityJSONEncoder(json.JSONEncoder):
  """Custom encoder for Entity objects."""
  def default(self, o):
    """Represents data from Equation objects as a dictionary.

    Args:
        o (Entity): Entity object that will be encoded.

    Returns:
        dict: The dictionary representation of the Entity object. If
          the object is not an Entity instance then the default
          representation is returned.
    """
    if isinstance(o, entity.Entity):
      return o.convert_to_dict()
    return super().default(o)

class EntityJSONEncoderOld(json.JSONEncoder):
  """Custom encoder for Entity objects.

  Only for backwards compatibility.
  """
  # TODO Remove when is no longer needed.
  def default(self, o):
    """Represents data from Entity objects as a dictionary.

    Args:
        o (Entity): Entity object that will be encoded.

    Returns:
        dict: The dictionary representation of the Entity object. If
          the object is not an Entity instance then the default
          representation is returned.
    """
    if isinstance(o, entity.Entity):
      return o.convert_to_old_dict()
    return super().default(o)
