# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../packages/OntologyBuilder/BehaviourLinker/Views/UIs/entity_merger.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_entity_merger(object):
    def setupUi(self, entity_merger):
        entity_merger.setObjectName("entity_merger")
        entity_merger.resize(493, 389)
        self.verticalLayout = QtWidgets.QVBoxLayout(entity_merger)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(entity_merger)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_variable = QtWidgets.QLabel(entity_merger)
        self.label_variable.setObjectName("label_variable")
        self.horizontalLayout_2.addWidget(self.label_variable)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.list_equations = QtWidgets.QListView(entity_merger)
        self.list_equations.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.list_equations.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_equations.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.list_equations.setObjectName("list_equations")
        self.verticalLayout.addWidget(self.list_equations)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pbutton_cancel = QtWidgets.QPushButton(entity_merger)
        self.pbutton_cancel.setObjectName("pbutton_cancel")
        self.horizontalLayout.addWidget(self.pbutton_cancel)
        self.pbutton_previous = QtWidgets.QPushButton(entity_merger)
        self.pbutton_previous.setObjectName("pbutton_previous")
        self.horizontalLayout.addWidget(self.pbutton_previous)
        self.pbutton_next = QtWidgets.QPushButton(entity_merger)
        self.pbutton_next.setObjectName("pbutton_next")
        self.horizontalLayout.addWidget(self.pbutton_next)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(entity_merger)
        QtCore.QMetaObject.connectSlotsByName(entity_merger)

    def retranslateUi(self, entity_merger):
        _translate = QtCore.QCoreApplication.translate
        entity_merger.setWindowTitle(_translate("entity_merger", "Entity merger"))
        self.label_2.setText(_translate("entity_merger", "Select the desired equation for:"))
        self.label_variable.setText(_translate("entity_merger", "TextLabel"))
        self.pbutton_cancel.setText(_translate("entity_merger", "Cancel"))
        self.pbutton_previous.setText(_translate("entity_merger", "Previous"))
        self.pbutton_next.setText(_translate("entity_merger", "Next"))
