# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/alberto/Documents/Promo/ProMo/packages/OntologyBuilder/BehaviourLinker/Views/UIs/variable_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_variable_editor(object):
    def setupUi(self, variable_editor):
        variable_editor.setObjectName("variable_editor")
        variable_editor.resize(558, 453)
        self.horizontalLayout = QtWidgets.QHBoxLayout(variable_editor)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(variable_editor)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.list_equations = QtWidgets.QListView(variable_editor)
        self.list_equations.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.list_equations.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_equations.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.list_equations.setObjectName("list_equations")
        self.verticalLayout_2.addWidget(self.list_equations)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbox_input = QtWidgets.QCheckBox(variable_editor)
        self.cbox_input.setObjectName("cbox_input")
        self.verticalLayout.addWidget(self.cbox_input)
        self.cbox_output = QtWidgets.QCheckBox(variable_editor)
        self.cbox_output.setObjectName("cbox_output")
        self.verticalLayout.addWidget(self.cbox_output)
        self.cbox_instantiation = QtWidgets.QCheckBox(variable_editor)
        self.cbox_instantiation.setObjectName("cbox_instantiation")
        self.verticalLayout.addWidget(self.cbox_instantiation)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pbutton_accept = QtWidgets.QPushButton(variable_editor)
        self.pbutton_accept.setObjectName("pbutton_accept")
        self.verticalLayout.addWidget(self.pbutton_accept)
        self.pbutton_cancel = QtWidgets.QPushButton(variable_editor)
        self.pbutton_cancel.setObjectName("pbutton_cancel")
        self.verticalLayout.addWidget(self.pbutton_cancel)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(variable_editor)
        QtCore.QMetaObject.connectSlotsByName(variable_editor)

    def retranslateUi(self, variable_editor):
        _translate = QtCore.QCoreApplication.translate
        variable_editor.setWindowTitle(_translate("variable_editor", "Variable Editor"))
        self.label_2.setText(_translate("variable_editor", "Available Equations"))
        self.cbox_input.setText(_translate("variable_editor", "Input"))
        self.cbox_output.setText(_translate("variable_editor", "Output"))
        self.cbox_instantiation.setText(_translate("variable_editor", "Instantiation"))
        self.pbutton_accept.setText(_translate("variable_editor", "Accept"))
        self.pbutton_cancel.setText(_translate("variable_editor", "Cancel"))
