# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'class_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(147, 193)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.select_input = QtWidgets.QRadioButton(Dialog)
        self.select_input.setObjectName("select_input")
        self.verticalLayout.addWidget(self.select_input)
        self.select_output = QtWidgets.QRadioButton(Dialog)
        self.select_output.setObjectName("select_output")
        self.verticalLayout.addWidget(self.select_output)
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.select_none = QtWidgets.QRadioButton(Dialog)
        self.select_none.setObjectName("select_none")
        self.verticalLayout.addWidget(self.select_none)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Classification"))
        self.select_input.setText(_translate("Dialog", "input"))
        self.select_output.setText(_translate("Dialog", "output"))
        self.radioButton.setText(_translate("Dialog", "instantiate"))
        self.select_none.setText(_translate("Dialog", "none"))
