# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equation_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(518, 573)
        self.info_group = QtWidgets.QGroupBox(Dialog)
        self.info_group.setGeometry(QtCore.QRect(10, 120, 181, 131))
        self.info_group.setObjectName("info_group")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.info_group)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.variable_symbol = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.variable_symbol.setObjectName("variable_symbol")
        self.verticalLayout.addWidget(self.variable_symbol)
        self.variable_ID = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.variable_ID.setObjectName("variable_ID")
        self.verticalLayout.addWidget(self.variable_ID)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(280, 120, 221, 131))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.equation_radio = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.equation_radio.setObjectName("equation_radio")
        self.verticalLayout_2.addWidget(self.equation_radio)
        self.instationate_radio = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.instationate_radio.setObjectName("instationate_radio")
        self.verticalLayout_2.addWidget(self.instationate_radio)
        self.equation_group = QtWidgets.QGroupBox(Dialog)
        self.equation_group.setGeometry(QtCore.QRect(10, 280, 491, 281))
        self.equation_group.setObjectName("equation_group")
        self.equiation_list = QtWidgets.QListWidget(self.equation_group)
        self.equiation_list.setGeometry(QtCore.QRect(10, 40, 471, 231))
        self.equiation_list.setObjectName("equiation_list")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 211, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushAccept = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushAccept.sizePolicy().hasHeightForWidth())
        self.pushAccept.setSizePolicy(sizePolicy)
        self.pushAccept.setObjectName("pushAccept")
        self.horizontalLayout_2.addWidget(self.pushAccept)
        self.pushCancel = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushCancel.sizePolicy().hasHeightForWidth())
        self.pushCancel.setSizePolicy(sizePolicy)
        self.pushCancel.setObjectName("pushCancel")
        self.horizontalLayout_2.addWidget(self.pushCancel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.info_group.setTitle(_translate("Dialog", "Selected Variable"))
        self.variable_symbol.setText(_translate("Dialog", "Symbol"))
        self.variable_ID.setText(_translate("Dialog", "ID"))
        self.groupBox.setTitle(_translate("Dialog", "Definition Method"))
        self.equation_radio.setText(_translate("Dialog", "Define Equation"))
        self.instationate_radio.setText(_translate("Dialog", "To be instantiated"))
        self.equation_group.setTitle(_translate("Dialog", "Select Equation"))
        self.pushAccept.setText(_translate("Dialog", "accept"))
        self.pushCancel.setText(_translate("Dialog", "cancel"))
