# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(519, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LED = QtWidgets.QPushButton(self.centralwidget)
        self.LED.setText("")
        self.LED.setObjectName("LED")
        self.horizontalLayout_2.addWidget(self.LED)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushMinimise = QtWidgets.QPushButton(self.centralwidget)
        self.pushMinimise.setText("")
        self.pushMinimise.setObjectName("pushMinimise")
        self.horizontalLayout.addWidget(self.pushMinimise)
        self.pushNormal = QtWidgets.QPushButton(self.centralwidget)
        self.pushNormal.setText("")
        self.pushNormal.setObjectName("pushNormal")
        self.horizontalLayout.addWidget(self.pushNormal)
        self.pushMaximise = QtWidgets.QPushButton(self.centralwidget)
        self.pushMaximise.setText("")
        self.pushMaximise.setObjectName("pushMaximise")
        self.horizontalLayout.addWidget(self.pushMaximise)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.pushSave = QtWidgets.QPushButton(self.centralwidget)
        self.pushSave.setObjectName("pushSave")
        self.horizontalLayout_6.addWidget(self.pushSave)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.pushExit = QtWidgets.QPushButton(self.centralwidget)
        self.pushExit.setObjectName("pushExit")
        self.horizontalLayout_6.addWidget(self.pushExit)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.tree_entities = QtWidgets.QTreeView(self.centralwidget)
        self.tree_entities.setMinimumSize(QtCore.QSize(320, 0))
        self.tree_entities.setMaximumSize(QtCore.QSize(500, 16777215))
        self.tree_entities.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tree_entities.setProperty("showDropIndicator", False)
        self.tree_entities.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tree_entities.setRootIsDecorated(True)
        self.tree_entities.setObjectName("tree_entities")
        self.tree_entities.header().setVisible(False)
        self.tree_entities.header().setDefaultSectionSize(57)
        self.gridLayout.addWidget(self.tree_entities, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BehaviourLinker"))
        self.pushSave.setText(_translate("MainWindow", "save"))
        self.pushExit.setText(_translate("MainWindow", "exit"))
        self.label.setText(_translate("MainWindow", "Defined Entities"))
