# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instantiation_dialog_HAP.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(807, 503)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.listValues = QtWidgets.QListWidget(Dialog)
        self.listValues.setObjectName("listValues")
        self.gridLayout.addWidget(self.listValues, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushInstantiate = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushInstantiate.sizePolicy().hasHeightForWidth())
        self.pushInstantiate.setSizePolicy(sizePolicy)
        self.pushInstantiate.setMinimumSize(QtCore.QSize(0, 40))
        self.pushInstantiate.setObjectName("pushInstantiate")
        self.horizontalLayout_3.addWidget(self.pushInstantiate)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushCancel = QtWidgets.QPushButton(Dialog)
        self.pushCancel.setMinimumSize(QtCore.QSize(0, 40))
        self.pushCancel.setObjectName("pushCancel")
        self.horizontalLayout_4.addWidget(self.pushCancel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.pushAccept = QtWidgets.QPushButton(Dialog)
        self.pushAccept.setMinimumSize(QtCore.QSize(0, 40))
        self.pushAccept.setObjectName("pushAccept")
        self.horizontalLayout_4.addWidget(self.pushAccept)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 1, 5, 1, 1)
        self.listVariables = QtWidgets.QListWidget(Dialog)
        self.listVariables.setObjectName("listVariables")
        self.gridLayout.addWidget(self.listVariables, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.listVariables, self.lineEdit)
        Dialog.setTabOrder(self.lineEdit, self.pushInstantiate)
        Dialog.setTabOrder(self.pushInstantiate, self.pushCancel)
        Dialog.setTabOrder(self.pushCancel, self.listValues)
        Dialog.setTabOrder(self.listValues, self.pushAccept)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushInstantiate.setText(_translate("Dialog", "instantiate"))
        self.pushCancel.setText(_translate("Dialog", "cancel"))
        self.pushAccept.setText(_translate("Dialog", "accept"))
        self.label.setText(_translate("Dialog", "variables"))
        self.label_2.setText(_translate("Dialog", "already defined values"))
        self.label_3.setText(_translate("Dialog", "enter value"))
