# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'variant_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 189)
        self.comboBoxVariations = QtWidgets.QComboBox(Dialog)
        self.comboBoxVariations.setGeometry(QtCore.QRect(50, 30, 611, 51))
        self.comboBoxVariations.setObjectName("comboBoxVariations")
        self.pushCancel = QtWidgets.QPushButton(Dialog)
        self.pushCancel.setGeometry(QtCore.QRect(500, 130, 80, 25))
        self.pushCancel.setObjectName("pushCancel")
        self.pushAccept = QtWidgets.QPushButton(Dialog)
        self.pushAccept.setGeometry(QtCore.QRect(610, 130, 80, 25))
        self.pushAccept.setObjectName("pushAccept")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushCancel.setText(_translate("Dialog", "PushButton"))
        self.pushAccept.setText(_translate("Dialog", "PushButton"))
