# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_show_variable_equation.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(724, 296)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(550, 240, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(70, 40, 571, 151))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_variable = QtWidgets.QLabel(self.widget)
        self.label_variable.setMinimumSize(QtCore.QSize(0, 25))
        self.label_variable.setObjectName("label_variable")
        self.gridLayout.addWidget(self.label_variable, 0, 0, 1, 1)
        self.picture_variable = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture_variable.sizePolicy().hasHeightForWidth())
        self.picture_variable.setSizePolicy(sizePolicy)
        self.picture_variable.setMinimumSize(QtCore.QSize(0, 25))
        self.picture_variable.setObjectName("picture_variable")
        self.gridLayout.addWidget(self.picture_variable, 0, 1, 1, 1)
        self.label_equation_0 = QtWidgets.QLabel(self.widget)
        self.label_equation_0.setMinimumSize(QtCore.QSize(0, 25))
        self.label_equation_0.setObjectName("label_equation_0")
        self.gridLayout.addWidget(self.label_equation_0, 1, 0, 1, 1)
        self.picture_equation_0 = QtWidgets.QLabel(self.widget)
        self.picture_equation_0.setMinimumSize(QtCore.QSize(0, 25))
        self.picture_equation_0.setObjectName("picture_equation_0")
        self.gridLayout.addWidget(self.picture_equation_0, 1, 1, 1, 1)
        self.label_equation_1 = QtWidgets.QLabel(self.widget)
        self.label_equation_1.setMinimumSize(QtCore.QSize(0, 25))
        self.label_equation_1.setObjectName("label_equation_1")
        self.gridLayout.addWidget(self.label_equation_1, 2, 0, 1, 1)
        self.picture_equation_1 = QtWidgets.QLabel(self.widget)
        self.picture_equation_1.setMinimumSize(QtCore.QSize(0, 25))
        self.picture_equation_1.setObjectName("picture_equation_1")
        self.gridLayout.addWidget(self.picture_equation_1, 2, 1, 1, 1)
        self.label_equation_2 = QtWidgets.QLabel(self.widget)
        self.label_equation_2.setMinimumSize(QtCore.QSize(0, 25))
        self.label_equation_2.setObjectName("label_equation_2")
        self.gridLayout.addWidget(self.label_equation_2, 3, 0, 1, 1)
        self.picture_equation_2 = QtWidgets.QLabel(self.widget)
        self.picture_equation_2.setMinimumSize(QtCore.QSize(0, 25))
        self.picture_equation_2.setObjectName("picture_equation_2")
        self.gridLayout.addWidget(self.picture_equation_2, 3, 1, 1, 1)
        self.label_equation_3 = QtWidgets.QLabel(self.widget)
        self.label_equation_3.setMinimumSize(QtCore.QSize(0, 25))
        self.label_equation_3.setObjectName("label_equation_3")
        self.gridLayout.addWidget(self.label_equation_3, 4, 0, 1, 1)
        self.picture_equation_3 = QtWidgets.QLabel(self.widget)
        self.picture_equation_3.setMinimumSize(QtCore.QSize(0, 25))
        self.picture_equation_3.setObjectName("picture_equation_3")
        self.gridLayout.addWidget(self.picture_equation_3, 4, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "exit"))
        self.label_variable.setText(_translate("Dialog", "variable"))
        self.picture_variable.setText(_translate("Dialog", "variable"))
        self.label_equation_0.setText(_translate("Dialog", "equation"))
        self.picture_equation_0.setText(_translate("Dialog", "equation"))
        self.label_equation_1.setText(_translate("Dialog", "equation"))
        self.picture_equation_1.setText(_translate("Dialog", "equation"))
        self.label_equation_2.setText(_translate("Dialog", "equation"))
        self.picture_equation_2.setText(_translate("Dialog", "equation"))
        self.label_equation_3.setText(_translate("Dialog", "equation"))
        self.picture_equation_3.setText(_translate("Dialog", "equation"))
