# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_show_variable_equation.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(687, 300)
        self.pushButtonExit = QtWidgets.QPushButton(Dialog)
        self.pushButtonExit.setGeometry(QtCore.QRect(10, 20, 89, 31))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 20, 571, 257))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_equation_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_equation_3.sizePolicy().hasHeightForWidth())
        self.label_equation_3.setSizePolicy(sizePolicy)
        self.label_equation_3.setMinimumSize(QtCore.QSize(100, 25))
        self.label_equation_3.setObjectName("label_equation_3")
        self.gridLayout.addWidget(self.label_equation_3, 3, 0, 1, 1)
        self.picture_equation_2 = QtWidgets.QLabel(self.layoutWidget)
        self.picture_equation_2.setMinimumSize(QtCore.QSize(0, 25))
        self.picture_equation_2.setObjectName("picture_equation_2")
        self.gridLayout.addWidget(self.picture_equation_2, 2, 1, 1, 1)
        self.label_equation_1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_equation_1.sizePolicy().hasHeightForWidth())
        self.label_equation_1.setSizePolicy(sizePolicy)
        self.label_equation_1.setMinimumSize(QtCore.QSize(100, 25))
        self.label_equation_1.setObjectName("label_equation_1")
        self.gridLayout.addWidget(self.label_equation_1, 1, 0, 1, 1)
        self.picture_equation_1 = QtWidgets.QLabel(self.layoutWidget)
        self.picture_equation_1.setMinimumSize(QtCore.QSize(0, 25))
        self.picture_equation_1.setObjectName("picture_equation_1")
        self.gridLayout.addWidget(self.picture_equation_1, 1, 1, 1, 1)
        self.label_equation_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_equation_2.sizePolicy().hasHeightForWidth())
        self.label_equation_2.setSizePolicy(sizePolicy)
        self.label_equation_2.setMinimumSize(QtCore.QSize(100, 25))
        self.label_equation_2.setObjectName("label_equation_2")
        self.gridLayout.addWidget(self.label_equation_2, 2, 0, 1, 1)
        self.label_equation_0 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_equation_0.sizePolicy().hasHeightForWidth())
        self.label_equation_0.setSizePolicy(sizePolicy)
        self.label_equation_0.setMinimumSize(QtCore.QSize(100, 25))
        self.label_equation_0.setObjectName("label_equation_0")
        self.gridLayout.addWidget(self.label_equation_0, 0, 0, 1, 1)
        self.picture_equation_3 = QtWidgets.QLabel(self.layoutWidget)
        self.picture_equation_3.setMinimumSize(QtCore.QSize(0, 25))
        self.picture_equation_3.setObjectName("picture_equation_3")
        self.gridLayout.addWidget(self.picture_equation_3, 3, 1, 1, 1)
        self.picture_equation_0 = QtWidgets.QLabel(self.layoutWidget)
        self.picture_equation_0.setMinimumSize(QtCore.QSize(0, 25))
        self.picture_equation_0.setObjectName("picture_equation_0")
        self.gridLayout.addWidget(self.picture_equation_0, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonExit.setText(_translate("Dialog", "exit"))
        self.label_equation_3.setText(_translate("Dialog", "equation_ID"))
        self.picture_equation_2.setText(_translate("Dialog", "equation_picture"))
        self.label_equation_1.setText(_translate("Dialog", "equation_ID"))
        self.picture_equation_1.setText(_translate("Dialog", "equation_picture"))
        self.label_equation_2.setText(_translate("Dialog", "equation_ID"))
        self.label_equation_0.setText(_translate("Dialog", "equation_ID"))
        self.picture_equation_3.setText(_translate("Dialog", "equation_picture"))
        self.picture_equation_0.setText(_translate("Dialog", "equation_picture"))
