# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_show_equation_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowEquationList(object):
    def setupUi(self, ShowEquationList):
        ShowEquationList.setObjectName("ShowEquationList")
        ShowEquationList.resize(659, 752)
        ShowEquationList.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(ShowEquationList)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(ShowEquationList)
        self.tableWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setIconSize(QtCore.QSize(100, 50))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(9)
        self.gridLayout.addWidget(self.tableWidget, 3, 0, 1, 1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.pushBack = QtWidgets.QPushButton(ShowEquationList)
        self.pushBack.setObjectName("pushBack")
        self.buttonLayout.addWidget(self.pushBack)
        self.pushAccept = QtWidgets.QPushButton(ShowEquationList)
        self.pushAccept.setObjectName("pushAccept")
        self.buttonLayout.addWidget(self.pushAccept)
        self.pushReject = QtWidgets.QPushButton(ShowEquationList)
        self.pushReject.setObjectName("pushReject")
        self.buttonLayout.addWidget(self.pushReject)
        self.pushNew = QtWidgets.QPushButton(ShowEquationList)
        self.pushNew.setObjectName("pushNew")
        self.buttonLayout.addWidget(self.pushNew)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.buttonLayout, 1, 0, 1, 1)
        self.labelAction = QtWidgets.QLabel(ShowEquationList)
        font = QtGui.QFont()
        font.setFamily("Latin Modern Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelAction.setFont(font)
        self.labelAction.setWordWrap(True)
        self.labelAction.setObjectName("labelAction")
        self.gridLayout.addWidget(self.labelAction, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)

        self.retranslateUi(ShowEquationList)
        QtCore.QMetaObject.connectSlotsByName(ShowEquationList)

    def retranslateUi(self, ShowEquationList):
        _translate = QtCore.QCoreApplication.translate
        ShowEquationList.setWindowTitle(_translate("ShowEquationList", "Dialog"))
        self.pushBack.setText(_translate("ShowEquationList", "back"))
        self.pushAccept.setText(_translate("ShowEquationList", "accept"))
        self.pushReject.setText(_translate("ShowEquationList", "reject"))
        self.pushNew.setText(_translate("ShowEquationList", "new"))
        self.labelAction.setText(_translate("ShowEquationList", "text"))
