# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_show_equation_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowEquationList(object):
    def setupUi(self, ShowEquationList):
        ShowEquationList.setObjectName("ShowEquationList")
        ShowEquationList.resize(659, 631)
        ShowEquationList.setSizeGripEnabled(True)
        self.tableWidget = QtWidgets.QTableWidget(ShowEquationList)
        self.tableWidget.setGeometry(QtCore.QRect(40, 100, 561, 511))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setIconSize(QtCore.QSize(100, 50))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(9)
        self.horizontalLayoutWidget = QtWidgets.QWidget(ShowEquationList)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 281, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.buttonLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setObjectName("buttonLayout")
        self.pushBack = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushBack.setObjectName("pushBack")
        self.buttonLayout.addWidget(self.pushBack)
        self.pushYes = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushYes.setObjectName("pushYes")
        self.buttonLayout.addWidget(self.pushYes)
        self.pushNo = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushNo.setObjectName("pushNo")
        self.buttonLayout.addWidget(self.pushNo)

        self.retranslateUi(ShowEquationList)
        QtCore.QMetaObject.connectSlotsByName(ShowEquationList)

    def retranslateUi(self, ShowEquationList):
        _translate = QtCore.QCoreApplication.translate
        ShowEquationList.setWindowTitle(_translate("ShowEquationList", "Dialog"))
        self.pushBack.setText(_translate("ShowEquationList", "back"))
        self.pushYes.setText(_translate("ShowEquationList", "yes"))
        self.pushNo.setText(_translate("ShowEquationList", "no"))
