# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/alberto/Documents/Promo/ProMo/packages/OntologyBuilder/BehaviourLinker/Views/UIs/insert_str.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_insert_str(object):
    def setupUi(self, insert_str):
        insert_str.setObjectName("insert_str")
        insert_str.resize(271, 117)
        self.verticalLayout = QtWidgets.QVBoxLayout(insert_str)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_prompt = QtWidgets.QLabel(insert_str)
        self.label_prompt.setObjectName("label_prompt")
        self.verticalLayout.addWidget(self.label_prompt)
        self.ledit_input = QtWidgets.QLineEdit(insert_str)
        self.ledit_input.setObjectName("ledit_input")
        self.verticalLayout.addWidget(self.ledit_input)
        self.frame = QtWidgets.QFrame(insert_str)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbutton_accept = QtWidgets.QPushButton(self.frame)
        self.pbutton_accept.setObjectName("pbutton_accept")
        self.horizontalLayout.addWidget(self.pbutton_accept)
        self.pbutton_cancel = QtWidgets.QPushButton(self.frame)
        self.pbutton_cancel.setObjectName("pbutton_cancel")
        self.horizontalLayout.addWidget(self.pbutton_cancel)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)

        self.retranslateUi(insert_str)
        QtCore.QMetaObject.connectSlotsByName(insert_str)

    def retranslateUi(self, insert_str):
        _translate = QtCore.QCoreApplication.translate
        insert_str.setWindowTitle(_translate("insert_str", "Dialog"))
        self.label_prompt.setText(_translate("insert_str", "Insert a name for the new entity:"))
        self.pbutton_accept.setText(_translate("insert_str", "Accept"))
        self.pbutton_cancel.setText(_translate("insert_str", "Cancel"))
