# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/alberto/Documents/Promo/ProMo/packages/OntologyBuilder/BehaviourLinker/Views/UIs/variable_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_variable_selection(object):
    def setupUi(self, variable_selection):
        variable_selection.setObjectName("variable_selection")
        variable_selection.resize(494, 149)
        self.verticalLayout = QtWidgets.QVBoxLayout(variable_selection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(variable_selection)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.list_variables = QtWidgets.QListView(variable_selection)
        self.list_variables.setMinimumSize(QtCore.QSize(0, 75))
        self.list_variables.setMaximumSize(QtCore.QSize(16777215, 80))
        self.list_variables.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.list_variables.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_variables.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.list_variables.setFlow(QtWidgets.QListView.LeftToRight)
        self.list_variables.setObjectName("list_variables")
        self.verticalLayout.addWidget(self.list_variables)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pbutton_accept = QtWidgets.QPushButton(variable_selection)
        self.pbutton_accept.setObjectName("pbutton_accept")
        self.horizontalLayout.addWidget(self.pbutton_accept)
        self.pbutton_cancel = QtWidgets.QPushButton(variable_selection)
        self.pbutton_cancel.setObjectName("pbutton_cancel")
        self.horizontalLayout.addWidget(self.pbutton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(variable_selection)
        QtCore.QMetaObject.connectSlotsByName(variable_selection)

    def retranslateUi(self, variable_selection):
        _translate = QtCore.QCoreApplication.translate
        variable_selection.setWindowTitle(_translate("variable_selection", "Add a new variable"))
        self.label.setText(_translate("variable_selection", "Select a variable to add."))
        self.pbutton_accept.setText(_translate("variable_selection", "Accept"))
        self.pbutton_cancel.setText(_translate("variable_selection", "Cancel"))
