# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/common/components/starting_dialog/view.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(349, 257)
        self.selection_list = QtWidgets.QListView(Dialog)
        self.selection_list.setGeometry(QtCore.QRect(10, 90, 321, 111))
        self.selection_list.setObjectName("selection_list")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 242, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushLeft = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushLeft.sizePolicy().hasHeightForWidth())
        self.pushLeft.setSizePolicy(sizePolicy)
        self.pushLeft.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushLeft.setText("")
        self.pushLeft.setIconSize(QtCore.QSize(60, 60))
        self.pushLeft.setAutoDefault(False)
        self.pushLeft.setObjectName("pushLeft")
        self.horizontalLayout.addWidget(self.pushLeft)
        self.pushCentre = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushCentre.sizePolicy().hasHeightForWidth())
        self.pushCentre.setSizePolicy(sizePolicy)
        self.pushCentre.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushCentre.setText("")
        self.pushCentre.setIconSize(QtCore.QSize(60, 60))
        self.pushCentre.setAutoDefault(False)
        self.pushCentre.setObjectName("pushCentre")
        self.horizontalLayout.addWidget(self.pushCentre)
        self.pushRight = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushRight.sizePolicy().hasHeightForWidth())
        self.pushRight.setSizePolicy(sizePolicy)
        self.pushRight.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushRight.setText("")
        self.pushRight.setIconSize(QtCore.QSize(60, 60))
        self.pushRight.setAutoDefault(False)
        self.pushRight.setObjectName("pushRight")
        self.horizontalLayout.addWidget(self.pushRight)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushLeft.setToolTip(_translate("Dialog", "exit dialog"))
        self.pushCentre.setToolTip(_translate("Dialog", "accept selection"))
        self.pushRight.setToolTip(_translate("Dialog", "accept selection"))
