import typing

from .context import IOContext, IOContextMember


class DataIO(typing.Protocol):
    def validate_repository_location(self, location: str) -> None: ...
    def get_context_member_options(
        self, context_member: IOContextMember, context: IOContext
    ) -> list[str]: ...
    def get_index_data(self, context: IOContext) -> typing.Any: ...
    def get_variable_data(self, context: IOContext) -> typing.Any: ...
