
"""

    Aim: building a semantic equation set from the equations generated by the OntologyEquationEditor module
    Why?: Using ontologies to write equations in a semantic form can help make promo models more understandable and accessible to a wider range of users. 
    It'll also provides a way to formally describe the relationships between the concepts in a promo-generated model, which can be useful 
    for integrating the models with other data sources or for validating the model against other sources of information.
    

    Main steps:

    1. Identify the concepts relevant to your model and define them using the ontology.
    2. Identify the relationships between the concepts and represent them using the ontology. This will help to connect the concepts in a structured and meaningful way.
    3. Use the relationships defined in the ontology to write the equations of your model in a semantic form, i.e., using the concepts and relationships defined in the ontology.
    4. Validate the equations against the ontology to ensure that they are consistent and make sense in the context of the domain.
    5. Publish the equations in a format that can be used by other software systems to understand and interpret the model. This could be in the form of RDF triples, OWL ontologies, or any other ontology representation format.

"""

__authors__ = 'Vinay Gautam: drvgautam@github.com'


from rdflib import Graph, Namespace, Literal

ontology_ns = Namespace("http://example.com/ontology/")
qudt_ns = Namespace("http://qudt.org/schema/qudt/")

# Create a graph
g = Graph()

# Create URIs for the physical process, pressure, volume, temperature, and number of moles variables
process_uri = ontology_ns.IdealGasLaw
pressure_uri = ontology_ns.Pressure
volume_uri = ontology_ns.Volume
temperature_uri = ontology_ns.Temperature
number_of_moles_uri = ontology_ns.NumberOfMoles

# Define the pressure, volume, temperature, and number of moles variables as subclasses of the PhysicalProcess class
g.add((pressure_uri, ontology_ns.rdf_type, qudt_ns.Pressure))
g.add((volume_uri, ontology_ns.rdf_type, qudt_ns.Volume))
g.add((temperature_uri, ontology_ns.rdf_type, qudt_ns.Temperature))
g.add((number_of_moles_uri, ontology_ns.rdf_type, qudt_ns.AmountOfSubstance))

# Assign units to the pressure, volume, temperature, and number of moles variables
g.add((pressure_uri, ontology_ns.unit, qudt_ns.Kilopascal))
g.add((volume_uri, ontology_ns.unit, qudt_ns.CubicMeter))
g.add((temperature_uri, ontology_ns.unit, qudt_ns.DegreeCelsius))
g.add((number_of_moles_uri, ontology_ns.unit, qudt_ns.Mole))

# Define the ideal gas law equation
g.add((process_uri, ontology_ns.hasEquation, Literal("PV = nRT")))

# Assign the pressure, volume, temperature, and number of moles variables to the ideal gas law
g.add((process_uri, ontology_ns.hasVariable, pressure_uri))
g.add((process_uri, ontology_ns.hasVariable, volume_uri))
g.add((process_uri, ontology_ns.hasVariable, temperature_uri))
g.add((process_uri, ontology_ns.hasVariable, number_of_moles_uri))

# Serialize and print the graph
print(g.serialize(format='turtle'))


# Example: Navier-Stokes Equation
"""
In this case, the qudt namespace is used to define the velocity, pressure, and viscosity variables as subclasses 
of the Velocity, Pressure, and DynamicViscosity classes respectively. The units for velocity, pressure, and 
viscosity are also taken from the QUDT ontology and assigned to the respective variables. 
The Navier-Stokes equations are added as properties of the FluidFlow class, and the velocity, pressure, 
and viscosity variables are assigned to the Navier-Stokes equations.
"""


"""
from rdflib import Graph, Namespace, Literal

ontology_ns = Namespace("http://example.com/ontology/")
qudt_ns = Namespace("http://qudt.org/schema/qudt/")

# Create a graph
g = Graph()

# Create URIs for the fluid flow, velocity, pressure, and viscosity variables
fluid_flow_uri = ontology_ns.FluidFlow
velocity_uri = ontology_ns.Velocity
pressure_uri = ontology_ns.Pressure
viscosity_uri = ontology_ns.Viscosity

# Define the velocity, pressure, and viscosity variables as subclasses of the PhysicalProcess class
g.add((velocity_uri, ontology_ns.rdf_type, qudt_ns.Velocity))
g.add((pressure_uri, ontology_ns.rdf_type, qudt_ns.Pressure))
g.add((viscosity_uri, ontology_ns.rdf_type, qudt_ns.DynamicViscosity))

# Assign units to the velocity, pressure, and viscosity variables
g.add((velocity_uri, ontology_ns.unit, qudt_ns.MeterPerSecond))
g.add((pressure_uri, ontology_ns.unit, qudt_ns.Pascal))
g.add((viscosity_uri, ontology_ns.unit, qudt_ns.PascalSecond))

# Define the Navier-Stokes equations
g.add((fluid_flow_uri, ontology_ns.hasEquation, Literal("u_t + u . grad(u) = - grad(p) + nu * Laplacian(u)")))
g.add((fluid_flow_uri, ontology_ns.hasEquation, Literal("div(u) = 0")))

# Assign the velocity, pressure, and viscosity variables to the Navier-Stokes equations
g.add((fluid_flow_uri, ontology_ns.hasVariable, velocity_uri))
g.add((fluid_flow_uri, ontology_ns.hasVariable, pressure_uri))
g.add((fluid_flow_uri, ontology_ns.hasVariable, viscosity_uri))

# Serialize and print the graph
print(g.serialize(format='turtle'))

"""


#Exaple-3: An extension of the example-2 (a set of equations)

"""
from rdflib import Graph, Namespace, Literal

ontology_ns = Namespace("http://example.com/ontology/")
qudt_ns = Namespace("http://qudt.org/schema/qudt/")

# Create a graph
g = Graph()

# Create URIs for the fluid flow, velocity, pressure, temperature, and viscosity variables
fluid_flow_uri = ontology_ns.FluidFlow
velocity_uri = ontology_ns.Velocity
pressure_uri = ontology_ns.Pressure
temperature_uri = ontology_ns.Temperature
viscosity_uri = ontology_ns.Viscosity

# Define the velocity, pressure, temperature, and viscosity variables as subclasses of the PhysicalProcess class
g.add((velocity_uri, ontology_ns.rdf_type, qudt_ns.Velocity))
g.add((pressure_uri, ontology_ns.rdf_type, qudt_ns.Pressure))
g.add((temperature_uri, ontology_ns.rdf_type, qudt_ns.Temperature))
g.add((viscosity_uri, ontology_ns.rdf_type, qudt_ns.DynamicViscosity))

# Assign units to the velocity, pressure, temperature, and viscosity variables
g.add((velocity_uri, ontology_ns.unit, qudt_ns.MeterPerSecond))
g.add((pressure_uri, ontology_ns.unit, qudt_ns.Pascal))
g.add((temperature_uri, ontology_ns.unit, qudt_ns.Kelvin))
g.add((viscosity_uri, ontology_ns.unit, qudt_ns.PascalSecond))

# Define the Navier-Stokes equations
g.add((fluid_flow_uri, ontology_ns.hasEquation, Literal("u_t + u . grad(u) = - grad(p) + nu * Laplacian(u)")))
g.add((fluid_flow_uri, ontology_ns.hasEquation, Literal("div(u) = 0")))

# Define the energy equation
g.add((fluid_flow_uri, ontology_ns.hasEquation, Literal("T_t + u . grad(T) = k * Laplacian(T)")))

# Assign the velocity, pressure, temperature, and viscosity variables to the Navier-Stokes and energy equations
g.add((fluid_flow_uri, ontology_ns.hasVariable, velocity_uri))
g.add((fluid_flow_uri, ontology_ns.hasVariable, pressure_uri))
g.add((fluid_flow_uri, ontology_ns.hasVariable, temperature_uri))
g.add((fluid_flow_uri, ontology_ns.hasVariable, viscosity_uri))

# Serialize and print the graph
print(g.serialize(format='turtle'))
"""


# A sample to writing equation set using OWL
"""
from rdflib import Graph, Literal, Namespace, RDF, RDFS, OWL
from rdflib.namespace import XSD

# Create the graph object
g = Graph()

# Define the namespace for qudt
qudt = Namespace("http://qudt.org/schema/qudt/")

# Define the units for pressure and temperature
pressure_unit = qudt["NewtonPerSquareMeter"]
temperature_unit = qudt["Kelvin"]

# Define the equations
eq1 = qudt["Pressure_Equation_1"]
eq2 = qudt["Pressure_Equation_2"]
eq3 = qudt["Temperature_Equation_1"]
eq4 = qudt["Temperature_Equation_2"]

# Define the variables
p1 = qudt["Pressure_1"]
p2 = qudt["Pressure_2"]
t1 = qudt["Temperature_1"]
t2 = qudt["Temperature_2"]

# Bind the variables to the equations
g.add((eq1, RDF.type, OWL.FunctionalProperty))
g.add((eq1, RDFS.range, pressure_unit))
g.add((eq1, RDFS.domain, t1))
g.add((eq1, RDFS.domain, p1))

g.add((eq2, RDF.type, OWL.FunctionalProperty))
g.add((eq2, RDFS.range, pressure_unit))
g.add((eq2, RDFS.domain, t2))
g.add((eq2, RDFS.domain, p2))

g.add((eq3, RDF.type, OWL.FunctionalProperty))
g.add((eq3, RDFS.range, temperature_unit))
g.add((eq3, RDFS.domain, p1))
g.add((eq3, RDFS.domain, t1))

g.add((eq4, RDF.type, OWL.FunctionalProperty))
g.add((eq4, RDFS.range, temperature_unit))
g.add((eq4, RDFS.domain, p2))
g.add((eq4, RDFS.domain, t2))

# Save the graph to a file in Turtle format
with open("model.ttl", "wb") as f:
    f.write(g.serialize(format="turtle"))
"""

# Writing the the above sample using only RDF and RDFS (and no OWL)

"""
from rdflib import Graph, Literal, Namespace, RDF, RDFS

# Create the graph object
g = Graph()

# Define the namespace for qudt
qudt = Namespace("http://qudt.org/schema/qudt/")

# Define the units for pressure and temperature
pressure_unit = qudt["NewtonPerSquareMeter"]
temperature_unit = qudt["Kelvin"]

# Define the equations
eq1 = qudt["Pressure_Equation_1"]
eq2 = qudt["Pressure_Equation_2"]
eq3 = qudt["Temperature_Equation_1"]
eq4 = qudt["Temperature_Equation_2"]

# Define the variables
p1 = qudt["Pressure_1"]
p2 = qudt["Pressure_2"]
t1 = qudt["Temperature_1"]
t2 = qudt["Temperature_2"]

# Bind the variables to the equations
g.add((eq1, RDF.type, RDF.Property))
g.add((eq1, RDFS.range, pressure_unit))
g.add((eq1, RDFS.domain, t1))
g.add((eq1, RDFS.domain, p1))

g.add((eq2, RDF.type, RDF.Property))
g.add((eq2, RDFS.range, pressure_unit))
g.add((eq2, RDFS.domain, t2))
g.add((eq2, RDFS.domain, p2))

g.add((eq3, RDF.type, RDF.Property))
g.add((eq3, RDFS.range, temperature_unit))
g.add((eq3, RDFS.domain, p1))
g.add((eq3, RDFS.domain, t1))

g.add((eq4, RDF.type, RDF.Property))
g.add((eq4, RDFS.range, temperature_unit))
g.add((eq4, RDFS.domain, p2))
g.add((eq4, RDFS.domain, t2))

# Save the graph to a file in Turtle format
with open("model.ttl", "wb") as f:
    f.write(g.serialize(format="turtle"))

"""