# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_get_qudt_iri.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QUDT_iri_fetcher(object):
    def setupUi(self, QUDT_iri_fetcher):
        QUDT_iri_fetcher.setObjectName("QUDT_iri_fetcher")
        QUDT_iri_fetcher.resize(446, 1064)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QUDT_iri_fetcher.sizePolicy().hasHeightForWidth())
        QUDT_iri_fetcher.setSizePolicy(sizePolicy)
        QUDT_iri_fetcher.setMinimumSize(QtCore.QSize(446, 0))
        self.tableWidget = QtWidgets.QTableWidget(QUDT_iri_fetcher)
        self.tableWidget.setGeometry(QtCore.QRect(10, 190, 421, 861))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(261, 0))
        self.tableWidget.setSizeIncrement(QtCore.QSize(1, 1))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayoutWidget = QtWidgets.QWidget(QUDT_iri_fetcher)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 321, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.push_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_1.sizePolicy().hasHeightForWidth())
        self.push_1.setSizePolicy(sizePolicy)
        self.push_1.setMinimumSize(QtCore.QSize(50, 40))
        self.push_1.setMaximumSize(QtCore.QSize(40, 40))
        self.push_1.setText("")
        self.push_1.setObjectName("push_1")
        self.horizontalLayout.addWidget(self.push_1)
        self.push_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_2.sizePolicy().hasHeightForWidth())
        self.push_2.setSizePolicy(sizePolicy)
        self.push_2.setMinimumSize(QtCore.QSize(40, 40))
        self.push_2.setMaximumSize(QtCore.QSize(40, 40))
        self.push_2.setText("")
        self.push_2.setObjectName("push_2")
        self.horizontalLayout.addWidget(self.push_2)
        self.push_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_3.sizePolicy().hasHeightForWidth())
        self.push_3.setSizePolicy(sizePolicy)
        self.push_3.setMinimumSize(QtCore.QSize(40, 40))
        self.push_3.setMaximumSize(QtCore.QSize(40, 40))
        self.push_3.setText("")
        self.push_3.setObjectName("push_3")
        self.horizontalLayout.addWidget(self.push_3)
        self.push_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_4.sizePolicy().hasHeightForWidth())
        self.push_4.setSizePolicy(sizePolicy)
        self.push_4.setMinimumSize(QtCore.QSize(40, 40))
        self.push_4.setMaximumSize(QtCore.QSize(40, 40))
        self.push_4.setText("")
        self.push_4.setObjectName("push_4")
        self.horizontalLayout.addWidget(self.push_4)
        self.lineEdit = QtWidgets.QLineEdit(QUDT_iri_fetcher)
        self.lineEdit.setGeometry(QtCore.QRect(20, 130, 251, 25))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(QUDT_iri_fetcher)
        QtCore.QMetaObject.connectSlotsByName(QUDT_iri_fetcher)

    def retranslateUi(self, QUDT_iri_fetcher):
        _translate = QtCore.QCoreApplication.translate
        QUDT_iri_fetcher.setWindowTitle(_translate("QUDT_iri_fetcher", "Form"))
        self.lineEdit.setToolTip(_translate("QUDT_iri_fetcher", "enter a term to filter with"))
