# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_namespace_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(953, 998)
        self.bush_LoadNameSpaceTable = QtWidgets.QPushButton(Form)
        self.bush_LoadNameSpaceTable.setGeometry(QtCore.QRect(30, 40, 89, 51))
        self.bush_LoadNameSpaceTable.setObjectName("bush_LoadNameSpaceTable")
        self.tableWidgetKnownNamespaces = QtWidgets.QTableWidget(Form)
        self.tableWidgetKnownNamespaces.setGeometry(QtCore.QRect(30, 130, 901, 831))
        self.tableWidgetKnownNamespaces.setMinimumSize(QtCore.QSize(481, 0))
        self.tableWidgetKnownNamespaces.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidgetKnownNamespaces.setWordWrap(False)
        self.tableWidgetKnownNamespaces.setObjectName("tableWidgetKnownNamespaces")
        self.tableWidgetKnownNamespaces.setColumnCount(2)
        self.tableWidgetKnownNamespaces.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidgetKnownNamespaces.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetKnownNamespaces.setHorizontalHeaderItem(1, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bush_LoadNameSpaceTable.setText(_translate("Form", "select \n"
" namespace"))
        item = self.tableWidgetKnownNamespaces.horizontalHeaderItem(0)
        item.setText(_translate("Form", "name"))
        item = self.tableWidgetKnownNamespaces.horizontalHeaderItem(1)
        item.setText(_translate("Form", "URI"))
