"""
Namespace editor implementatation logic for adding/removing names, displaying log info stats from sqlite database

"""
__authors__ = 'Vinay Gautam: drvgautam@github.com'


from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


try:
    _fromUtf8 = QStringListModel.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName(_fromUtf8("Preferences"))
        Preferences.resize(685, 441)
        # icon = QIcon()
        # icon.addPixmap(QPixmap(_fromUtf8(":/images/preferences.png")), QIcon.Normal, QIcon.Off)
        # Preferences.setWindowIcon(icon)
        self.gridLayout = QGridLayout(Preferences)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.progressBarLoad = QProgressBar(Preferences)
        self.progressBarLoad.setMinimumSize(QSize(100, 10))
        self.progressBarLoad.setMaximumSize(QSize(140, 12))
        self.progressBarLoad.setProperty("value", 40)
        self.progressBarLoad.setTextVisible(False)
        self.progressBarLoad.setObjectName(_fromUtf8("progressBarLoad"))
        self.gridLayout.addWidget(self.progressBarLoad, 1, 0, 1, 1)
        self.tabWidgetPreferences = QTabWidget(Preferences)
        self.tabWidgetPreferences.setContextMenuPolicy(Qt.PreventContextMenu)
        self.tabWidgetPreferences.setTabPosition(QTabWidget.North)
        self.tabWidgetPreferences.setIconSize(QSize(16, 12))
        self.tabWidgetPreferences.setObjectName(_fromUtf8("tabWidgetPreferences"))
        self.tabNamespaces = QWidget()
        self.tabNamespaces.setObjectName(_fromUtf8("tabNamespaces"))
        self.gridLayout_4 = QGridLayout(self.tabNamespaces)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btnDeleteNamespace = QPushButton(self.tabNamespaces)
        self.btnDeleteNamespace.setMaximumSize(QSize(150, 16777215))
        self.btnDeleteNamespace.setObjectName(_fromUtf8("btnDeleteNamespace"))
        self.gridLayout_4.addWidget(self.btnDeleteNamespace, 1, 2, 1, 1)
        self.btnRestoreDefaultNamespaces = QPushButton(self.tabNamespaces)
        self.btnRestoreDefaultNamespaces.setMaximumSize(QSize(150, 16777215))
        self.btnRestoreDefaultNamespaces.setObjectName(_fromUtf8("btnRestoreDefaultNamespaces"))
        self.gridLayout_4.addWidget(self.btnRestoreDefaultNamespaces, 1, 3, 1, 1)
        self.btnAddNamespace = QPushButton(self.tabNamespaces)
        self.btnAddNamespace.setMaximumSize(QSize(150, 16777215))
        self.btnAddNamespace.setObjectName(_fromUtf8("btnAddNamespace"))
        self.gridLayout_4.addWidget(self.btnAddNamespace, 1, 1, 1, 1)
        self.tableWidgetKnownNamespaces = QTableWidget(self.tabNamespaces)
        self.tableWidgetKnownNamespaces.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidgetKnownNamespaces.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidgetKnownNamespaces.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWidgetKnownNamespaces.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidgetKnownNamespaces.setShowGrid(True)
        self.tableWidgetKnownNamespaces.setObjectName(_fromUtf8("tableWidgetKnownNamespaces"))
        self.tableWidgetKnownNamespaces.setColumnCount(2)
        self.tableWidgetKnownNamespaces.setRowCount(0)
        item = QTableWidgetItem()
        self.tableWidgetKnownNamespaces.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidgetKnownNamespaces.setHorizontalHeaderItem(1, item)
        self.tableWidgetKnownNamespaces.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetKnownNamespaces.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.tableWidgetKnownNamespaces, 0, 0, 1, 4)
        # icon3 = QIcon()
        # icon3.addPixmap(QPixmap(_fromUtf8(":/images/namespaces.png")), QIcon.Normal, QIcon.Off)
        self.tabWidgetPreferences.addTab(self.tabNamespaces, _fromUtf8(""))
        self.tabLog = QWidget()
        self.tabLog.setObjectName(_fromUtf8("tabLog"))
        self.gridLayout_3 = QGridLayout(self.tabLog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btnClearLog = QPushButton(self.tabLog)
        self.btnClearLog.setMaximumSize(QSize(100, 16777215))
        self.btnClearLog.setObjectName(_fromUtf8("btnClearLog"))
        self.gridLayout_3.addWidget(self.btnClearLog, 1, 1, 1, 1)
        self.tableWidgetLogEntries = QTableWidget(self.tabLog)
        self.tableWidgetLogEntries.setContextMenuPolicy(Qt.PreventContextMenu)
        self.tableWidgetLogEntries.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidgetLogEntries.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWidgetLogEntries.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidgetLogEntries.setShowGrid(True)
        self.tableWidgetLogEntries.setObjectName(_fromUtf8("tableWidgetLogEntries"))
        self.tableWidgetLogEntries.setColumnCount(2)
        self.tableWidgetLogEntries.setRowCount(0)
        item = QTableWidgetItem()
        self.tableWidgetLogEntries.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidgetLogEntries.setHorizontalHeaderItem(1, item)
        self.tableWidgetLogEntries.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetLogEntries.horizontalHeader().setDefaultSectionSize(115)
        self.tableWidgetLogEntries.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidgetLogEntries.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetLogEntries.verticalHeader().setDefaultSectionSize(30)
        self.gridLayout_3.addWidget(self.tableWidgetLogEntries, 0, 0, 1, 2)
        icon5 = QIcon()
        icon5.addPixmap(QPixmap(_fromUtf8(":/images/log.png")), QIcon.Normal, QIcon.Off)
        self.tabWidgetPreferences.addTab(self.tabLog, icon5, _fromUtf8(""))
        self.tabDatabase = QWidget()
        self.tabDatabase.setObjectName(_fromUtf8("tabDatabase"))
        self.gridLayout_8 = QGridLayout(self.tabDatabase)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tableWidgetDatabaseStats = QTableWidget(self.tabDatabase)
        self.tableWidgetDatabaseStats.setMaximumSize(QSize(16777215, 182))
        self.tableWidgetDatabaseStats.setContextMenuPolicy(Qt.PreventContextMenu)
        self.tableWidgetDatabaseStats.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidgetDatabaseStats.setObjectName(_fromUtf8("tableWidgetDatabaseStats"))
        self.tableWidgetDatabaseStats.setColumnCount(1)
        self.tableWidgetDatabaseStats.setRowCount(2)
        item = QTableWidgetItem()
        self.tableWidgetDatabaseStats.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidgetDatabaseStats.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tableWidgetDatabaseStats.setHorizontalHeaderItem(0, item)
        self.tableWidgetDatabaseStats.horizontalHeader().setVisible(False)
        self.tableWidgetDatabaseStats.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidgetDatabaseStats.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_8.addWidget(self.tableWidgetDatabaseStats, 0, 0, 1, 5)
        self.btnExportDatabase = QPushButton(self.tabDatabase)
        self.btnExportDatabase.setMaximumSize(QSize(110, 16777215))
        self.btnExportDatabase.setObjectName(_fromUtf8("btnExportDatabase"))
        self.gridLayout_8.addWidget(self.btnExportDatabase, 2, 2, 1, 1)
        spacerItem1 = QSpacerItem(20, 115, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 1, 1, 1, 1)
        self.btnImportDatabase = QPushButton(self.tabDatabase)
        self.btnImportDatabase.setMaximumSize(QSize(110, 16777215))
        self.btnImportDatabase.setObjectName(_fromUtf8("btnImportDatabase"))
        self.gridLayout_8.addWidget(self.btnImportDatabase, 2, 3, 1, 1)
        self.btnResetToDefaultDatabase = QPushButton(self.tabDatabase)
        self.btnResetToDefaultDatabase.setMaximumSize(QSize(110, 16777215))
        self.btnResetToDefaultDatabase.setObjectName(_fromUtf8("btnResetToDefaultDatabase"))
        self.gridLayout_8.addWidget(self.btnResetToDefaultDatabase, 2, 4, 1, 1)
        icon6 = QIcon()
        icon6.addPixmap(QPixmap(_fromUtf8(":/images/database.png")), QIcon.Normal, QIcon.Off)
        self.tabWidgetPreferences.addTab(self.tabDatabase, icon6, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidgetPreferences, 0, 0, 1, 4)
        self.btnClose = QPushButton(Preferences)
        self.btnClose.setMaximumSize(QSize(75, 16777215))
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.gridLayout.addWidget(self.btnClose, 1, 3, 1, 1)

        self.retranslateUi(Preferences)
        self.tabWidgetPreferences.setCurrentIndex(1)
        QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        Preferences.setWindowTitle(_translate("Namespace Manager", "Namespace Manager", None))
        Preferences.setWhatsThis(_translate("Preferences", "Preferences window", None))
        self.progressBarLoad.setToolTip(_translate("Preferences", "Loading..", None))
        
        self.btnDeleteNamespace.setToolTip(_translate("Preferences", "Delete selected namespace", None))
        self.btnDeleteNamespace.setWhatsThis(_translate("Preferences", "Delete selected endpoint", None))
        self.btnDeleteNamespace.setText(_translate("Preferences", "Delete namespace", None))
        self.btnRestoreDefaultNamespaces.setToolTip(_translate("Preferences", "Restore default namespaces", None))
        self.btnRestoreDefaultNamespaces.setWhatsThis(_translate("Preferences", "Delete selected endpoint", None))
        self.btnRestoreDefaultNamespaces.setText(_translate("Preferences", "Restore default", None))
        self.btnAddNamespace.setToolTip(_translate("Preferences", "Add a new namespace", None))
        self.btnAddNamespace.setWhatsThis(_translate("Preferences", "Add a new endpoint", None))
        self.btnAddNamespace.setText(_translate("Preferences", "Add namespace", None))
        self.tableWidgetKnownNamespaces.setToolTip(_translate("Preferences", "List of all stored namespaces", None))
        self.tableWidgetKnownNamespaces.setWhatsThis(_translate("Preferences", "A list of all known endpoints", None))
        item = self.tableWidgetKnownNamespaces.horizontalHeaderItem(0)
        item.setText(_translate("Preferences", "Prefix", None))
        item = self.tableWidgetKnownNamespaces.horizontalHeaderItem(1)
        item.setText(_translate("Preferences", "URI", None))
        self.tabWidgetPreferences.setTabText(self.tabWidgetPreferences.indexOf(self.tabNamespaces), _translate("Preferences", "Namespaces", None))
        self.tabWidgetPreferences.setTabToolTip(self.tabWidgetPreferences.indexOf(self.tabNamespaces), _translate("Preferences", "Namespace preferences", None))
        self.btnClearLog.setToolTip(_translate("Preferences", "Clear log entries", None))
        self.btnClearLog.setWhatsThis(_translate("Preferences", "Delete log entries", None))
        self.btnClearLog.setText(_translate("Preferences", "Clear log", None))
        self.tableWidgetLogEntries.setToolTip(_translate("Preferences", "List of log entries", None))
        self.tableWidgetLogEntries.setWhatsThis(_translate("Preferences", "List of log entries", None))
        item = self.tableWidgetLogEntries.horizontalHeaderItem(0)
        item.setText(_translate("Preferences", "Time", None))
        item = self.tableWidgetLogEntries.horizontalHeaderItem(1)
        item.setText(_translate("Preferences", "Description", None))
        self.tabWidgetPreferences.setTabText(self.tabWidgetPreferences.indexOf(self.tabLog), _translate("Preferences", "Log", None))
        self.tabWidgetPreferences.setTabToolTip(self.tabWidgetPreferences.indexOf(self.tabLog), _translate("Preferences", "Log preferences", None))
        
        item = self.tableWidgetDatabaseStats.verticalHeaderItem(0)
        item.setText(_translate("Preferences", "Known namespaces", None))
        
        item = self.tableWidgetDatabaseStats.verticalHeaderItem(1)
        item.setText(_translate("Preferences", "Log entries", None))
        item = self.tableWidgetDatabaseStats.horizontalHeaderItem(0)
        item.setText(_translate("Preferences", "Value", None))
        self.btnExportDatabase.setToolTip(_translate("Preferences", "Export current database", None))
        # self.btnExportDatabase.setWhatsThis(_translate("Preferences", "Save changes made in General tab", None))
        self.btnExportDatabase.setText(_translate("Preferences", "Export database...", None))
        self.btnImportDatabase.setToolTip(_translate("Preferences", "Select a database to import", None))
        # self.btnImportDatabase.setWhatsThis(_translate("Preferences", "Save changes made in General tab", None))
        self.btnImportDatabase.setText(_translate("Preferences", "Import database...", None))
        self.btnResetToDefaultDatabase.setToolTip(_translate("Preferences", "Reset to default database", None))
        # self.btnResetToDefaultDatabase.setWhatsThis(_translate("Preferences", "Save changes made in General tab", None))
        self.btnResetToDefaultDatabase.setText(_translate("Preferences", "Reset to default", None))
        self.tabWidgetPreferences.setTabText(self.tabWidgetPreferences.indexOf(self.tabDatabase), _translate("Preferences", "Database", None))
        self.tabWidgetPreferences.setTabToolTip(self.tabWidgetPreferences.indexOf(self.tabDatabase), _translate("Preferences", "Database preferences", None))
        self.btnClose.setToolTip(_translate("Preferences", "Close Preferences window", None))
        self.btnClose.setWhatsThis(_translate("Preferences", "Close Preferences window", None))
        self.btnClose.setText(_translate("Preferences", "Close", None))

