# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qudt_fetch.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QUDT_fetcher(object):
    def setupUi(self, QUDT_fetcher):
        QUDT_fetcher.setObjectName("QUDT_fetcher")
        QUDT_fetcher.resize(505, 226)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QUDT_fetcher.sizePolicy().hasHeightForWidth())
        QUDT_fetcher.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget = QtWidgets.QWidget(QUDT_fetcher)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 70, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.push_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.push_1.setObjectName("push_1")
        self.verticalLayout.addWidget(self.push_1)
        self.push_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.push_2.setObjectName("push_2")
        self.verticalLayout.addWidget(self.push_2)

        self.retranslateUi(QUDT_fetcher)
        QtCore.QMetaObject.connectSlotsByName(QUDT_fetcher)

    def retranslateUi(self, QUDT_fetcher):
        _translate = QtCore.QCoreApplication.translate
        QUDT_fetcher.setWindowTitle(_translate("QUDT_fetcher", "Form"))
        self.push_1.setText(_translate("QUDT_fetcher", "get qudt"))
        self.push_2.setText(_translate("QUDT_fetcher", "extract SI units"))
