# Form implementation generated from reading ui file 'ui_code_generator.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 556)
        self.LED = QtWidgets.QPushButton(parent=Dialog)
        self.LED.setGeometry(QtCore.QRect(10, 20, 32, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.LED.sizePolicy().hasHeightForWidth())
        self.LED.setSizePolicy(sizePolicy)
        self.LED.setText("")
        self.LED.setObjectName("LED")
        self.pushExit = QtWidgets.QPushButton(parent=Dialog)
        self.pushExit.setGeometry(QtCore.QRect(80, 20, 46, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushExit.sizePolicy().hasHeightForWidth())
        self.pushExit.setSizePolicy(sizePolicy)
        self.pushExit.setText("")
        self.pushExit.setAutoDefault(False)
        self.pushExit.setDefault(True)
        self.pushExit.setObjectName("pushExit")
        self.textOutput = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.textOutput.setGeometry(QtCore.QRect(20, 80, 351, 441))
        self.textOutput.setObjectName("textOutput")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushExit.setToolTip(_translate("Dialog", "<html><head/><body><p>- compiles into all available code languages</p><p>- writes equations and variables as well as index file</p><p>- generates latex files with dot graphs</p></body></html>"))
