# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_code_generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CodeGenerator(object):
    def setupUi(self, CodeGenerator):
        CodeGenerator.setObjectName("CodeGenerator")
        CodeGenerator.resize(400, 556)
        self.LED = QtWidgets.QPushButton(CodeGenerator)
        self.LED.setGeometry(QtCore.QRect(10, 20, 32, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.LED.sizePolicy().hasHeightForWidth())
        self.LED.setSizePolicy(sizePolicy)
        self.LED.setText("")
        self.LED.setObjectName("LED")
        self.pushExit = QtWidgets.QPushButton(CodeGenerator)
        self.pushExit.setGeometry(QtCore.QRect(80, 20, 46, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushExit.sizePolicy().hasHeightForWidth())
        self.pushExit.setSizePolicy(sizePolicy)
        self.pushExit.setText("")
        self.pushExit.setAutoDefault(False)
        self.pushExit.setDefault(True)
        self.pushExit.setObjectName("pushExit")
        self.textOutput = QtWidgets.QPlainTextEdit(CodeGenerator)
        self.textOutput.setGeometry(QtCore.QRect(20, 80, 351, 441))
        self.textOutput.setObjectName("textOutput")
        self.pushInfo = QtWidgets.QPushButton(CodeGenerator)
        self.pushInfo.setGeometry(QtCore.QRect(150, 20, 46, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushInfo.sizePolicy().hasHeightForWidth())
        self.pushInfo.setSizePolicy(sizePolicy)
        self.pushInfo.setText("")
        self.pushInfo.setAutoDefault(False)
        self.pushInfo.setDefault(True)
        self.pushInfo.setObjectName("pushInfo")

        self.retranslateUi(CodeGenerator)
        QtCore.QMetaObject.connectSlotsByName(CodeGenerator)

    def retranslateUi(self, CodeGenerator):
        _translate = QtCore.QCoreApplication.translate
        CodeGenerator.setWindowTitle(_translate("CodeGenerator", "Dialog"))
        self.pushExit.setToolTip(_translate("CodeGenerator", "<html><head/><body><p>- compiles into all available code languages</p><p>- writes equations and variables as well as index file</p><p>- generates latex files with dot graphs</p></body></html>"))
        self.pushInfo.setToolTip(_translate("CodeGenerator", "<html><head/><body><p>- compiles into all available code languages</p><p>- writes equations and variables as well as index file</p><p>- generates latex files with dot graphs</p></body></html>"))
