# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_code_generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CodeGenerator(object):
    def setupUi(self, CodeGenerator):
        CodeGenerator.setObjectName("CodeGenerator")
        CodeGenerator.resize(387, 446)
        self.centralwidget = QtWidgets.QWidget(CodeGenerator)
        self.centralwidget.setObjectName("centralwidget")
        self.pushInfo = QtWidgets.QPushButton(self.centralwidget)
        self.pushInfo.setGeometry(QtCore.QRect(170, 10, 46, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushInfo.sizePolicy().hasHeightForWidth())
        self.pushInfo.setSizePolicy(sizePolicy)
        self.pushInfo.setText("")
        self.pushInfo.setAutoDefault(False)
        self.pushInfo.setDefault(True)
        self.pushInfo.setObjectName("pushInfo")
        self.pushExit = QtWidgets.QPushButton(self.centralwidget)
        self.pushExit.setGeometry(QtCore.QRect(100, 10, 46, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushExit.sizePolicy().hasHeightForWidth())
        self.pushExit.setSizePolicy(sizePolicy)
        self.pushExit.setText("")
        self.pushExit.setAutoDefault(False)
        self.pushExit.setDefault(True)
        self.pushExit.setObjectName("pushExit")
        self.LED = QtWidgets.QPushButton(self.centralwidget)
        self.LED.setGeometry(QtCore.QRect(30, 10, 32, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.LED.sizePolicy().hasHeightForWidth())
        self.LED.setSizePolicy(sizePolicy)
        self.LED.setText("")
        self.LED.setObjectName("LED")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(40, 80, 300, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(150, 200))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.textStdout = QtWidgets.QPlainTextEdit(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textStdout.setFont(font)
        self.textStdout.setObjectName("textStdout")
        self.textStderr = QtWidgets.QPlainTextEdit(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textStderr.setFont(font)
        self.textStderr.setObjectName("textStderr")
        CodeGenerator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CodeGenerator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 387, 22))
        self.menubar.setObjectName("menubar")
        CodeGenerator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CodeGenerator)
        self.statusbar.setObjectName("statusbar")
        CodeGenerator.setStatusBar(self.statusbar)

        self.retranslateUi(CodeGenerator)
        QtCore.QMetaObject.connectSlotsByName(CodeGenerator)

    def retranslateUi(self, CodeGenerator):
        _translate = QtCore.QCoreApplication.translate
        CodeGenerator.setWindowTitle(_translate("CodeGenerator", "MainWindow"))
        self.pushInfo.setToolTip(_translate("CodeGenerator", "<html><head/><body><p>- compiles into all available code languages</p><p>- writes equations and variables as well as index file</p><p>- generates latex files with dot graphs</p></body></html>"))
        self.pushExit.setToolTip(_translate("CodeGenerator", "<html><head/><body><p>- compiles into all available code languages</p><p>- writes equations and variables as well as index file</p><p>- generates latex files with dot graphs</p></body></html>"))
